<?php
$state_list = array (
    'NULL'	=>	'Select a State/Province',

    'AAB'	=>	'---------------',

    'AL'	=>	'AL - Alabama',
    'AK'	=>	'AK - Alaska',
    'AZ'	=>	'AZ - Arizona',
    'AR'	=>	'AR - Arkansas',
    'CA'	=>	'CA - California',
    'CO'	=>	'CO - Colorado',
    'CT'	=>	'CT - Connecticut',
    'DE'	=>	'DE - Delaware',
    'DC'	=>	'DC - District of Columbia',
    'FL'	=>	'FL - Florida',
    'GA'	=>	'GA - Georgia',
    'HI'	=>	'HI - Hawaii',
    'ID'	=>	'ID - Idaho',
    'IL'	=>	'IL - Illinois',
    'IN'	=>	'IN - Indiana',
    'IA'	=>	'IA - Iowa',
    'KS'	=>	'KS - Kansas',
    'KY'	=>	'KY - Kentucky',
    'LA'	=>	'LA - Louisiana',
    'ME'	=>	'ME - Maine',
    'MD'	=>	'MD - Maryland',
    'MA'	=>	'MA - Massachusetts',
    'MI'	=>	'MI - Michigan',
    'MN'	=>	'MN - Minnesota',
    'MS'	=>	'MS - Mississippi',
    'MO'	=>	'MO - Missouri',
    'MT'	=>	'MT - Montana',
    'NE'	=>	'NE - Nebraska',
    'NV'	=>	'NV - Nevada',
    'NH'	=>	'NH - New Hampshire',
    'NJ'	=>	'NJ - New Jersey',
    'NM'	=>	'NM - New Mexico',
    'NY'	=>	'NY - New York',
    'NC'	=>	'NC - North Carolina',
    'ND'	=>	'ND - North Dakota',
    'OH'	=>	'OH - Ohio',
    'OK'	=>	'OK - Oklahoma',
    'OR'	=>	'OR - Oregon',
    'PA'	=>	'PA - Pennsylvania',
    'RI'	=>	'RI - Rhode Island',
    'SC'	=>	'SC - South Carolina',
    'SD'	=>	'SD - South Dakota',
    'TN'	=>	'TN - Tennessee',
    'TX'	=>	'TX - Texas',
    'UT'	=>	'UT - Utah',
    'VT'	=>	'VT - Vermont',
    'VA'	=>	'VA - Virginia',
    'WA'	=>	'WA - Washington',
    'WV'	=>	'WV - West Virginia',
    'WI'	=>	'WI - Wisconsin',
    'WY'	=>	'WY - Wyoming',
    '0'		=>	'---------------',
    'AE'	=>	'AE - Armed Forces Africa',
    'AA'	=>	'AA - Armed Forces Americas (except Canada)',
    'AE'	=>	'AE - Armed Forces Canada',
    'AE'	=>	'AE - Armed Forces Europe',
    'AE'	=>	'AE - Armed Forces Middle East',
    'AP'	=>	'AP - Armed Forces Pacific',
    
    'AAC'	=>	'---------------',
    
    'AB'	=>	'AB - Alberta',
    'BC'	=>	'BC - British Columbia',
    'MB'	=>	'MB - Manitoba',
    'NB'	=>	'NB - New Brunswick',
    'NL'	=>	'NL - Newfoundland and Labrador',
    'NT'	=>	'NT - Northwest Territories',
    'NS'	=>	'NS - Nova Scotia',
    'NU'	=>	'NU - Nunavut',
    'ON'	=>	'ON - Ontario',
    'PE'	=>	'PE - Prince Edward Island',
    'QC'	=>	'QC - Quebec',
    'SK'	=>	'SK - Saskatchewan',
    'YT'	=>	'YT - Yukon',
    
    'AAD'	=>	'---------------',
    
    'AS'	=>	'AS - American Samoa',
    'FM'	=>	'FM - Federated States of Micronesia',
    'GU'	=>	'GU - Guam',
    'MH'	=>	'MH - Marshall Islands',
    'MP'	=>	'MP - Northern Mariana Islands',
    'PW'	=>	'PW - Palau',
    'PR'	=>	'PR - Puerto Rico',
    'VI'	=>	'VI - Virgin Islands',
    
    'AAE'	=>	'---------------',
    
    'XX'	=>	'XX - Other State/Province/Territory',
);

$state_params = 'class=mediumSelect' ;

echo form_dropdown('state', $state_list, set_value('state', $user_profile['state']), $state_params);