<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * --------------------------
 * Config: State List
 * --------------------------
 * Default value:
 * $config['state_list'] = array();
 * 
 * Contains the complete list of states
 */
$config['state_list'] = array (
    'NULL'	=>	'Select a State/Province',

    'AAB'	=>	'---------------',

    'AL'	=>	'AL - Alabama',
    'AK'	=>	'AK - Alaska',
    'AZ'	=>	'AZ - Arizona',
    'AR'	=>	'AR - Arkansas',
    'CA'	=>	'CA - California',
    'CO'	=>	'CO - Colorado',
    'CT'	=>	'CT - Connecticut',
    'DE'	=>	'DE - Delaware',
    'DC'	=>	'DC - District of Columbia',
    'FL'	=>	'FL - Florida',
    'GA'	=>	'GA - Georgia',
    'HI'	=>	'HI - Hawaii',
    'ID'	=>	'ID - Idaho',
    'IL'	=>	'IL - Illinois',
    'IN'	=>	'IN - Indiana',
    'IA'	=>	'IA - Iowa',
    'KS'	=>	'KS - Kansas',
    'KY'	=>	'KY - Kentucky',
    'LA'	=>	'LA - Louisiana',
    'ME'	=>	'ME - Maine',
    'MD'	=>	'MD - Maryland',
    'MA'	=>	'MA - Massachusetts',
    'MI'	=>	'MI - Michigan',
    'MN'	=>	'MN - Minnesota',
    'MS'	=>	'MS - Mississippi',
    'MO'	=>	'MO - Missouri',
    'MT'	=>	'MT - Montana',
    'NE'	=>	'NE - Nebraska',
    'NV'	=>	'NV - Nevada',
    'NH'	=>	'NH - New Hampshire',
    'NJ'	=>	'NJ - New Jersey',
    'NM'	=>	'NM - New Mexico',
    'NY'	=>	'NY - New York',
    'NC'	=>	'NC - North Carolina',
    'ND'	=>	'ND - North Dakota',
    'OH'	=>	'OH - Ohio',
    'OK'	=>	'OK - Oklahoma',
    'OR'	=>	'OR - Oregon',
    'PA'	=>	'PA - Pennsylvania',
    'RI'	=>	'RI - Rhode Island',
    'SC'	=>	'SC - South Carolina',
    'SD'	=>	'SD - South Dakota',
    'TN'	=>	'TN - Tennessee',
    'TX'	=>	'TX - Texas',
    'UT'	=>	'UT - Utah',
    'VT'	=>	'VT - Vermont',
    'VA'	=>	'VA - Virginia',
    'WA'	=>	'WA - Washington',
    'WV'	=>	'WV - West Virginia',
    'WI'	=>	'WI - Wisconsin',
    'WY'	=>	'WY - Wyoming',
    '0'		=>	'---------------',
    'AE'	=>	'AE - Armed Forces Africa',
    'AA'	=>	'AA - Armed Forces Americas (except Canada)',
    'AE'	=>	'AE - Armed Forces Canada',
    'AE'	=>	'AE - Armed Forces Europe',
    'AE'	=>	'AE - Armed Forces Middle East',
    'AP'	=>	'AP - Armed Forces Pacific',
    
    'AAC'	=>	'---------------',
    
    'AB'	=>	'AB - Alberta',
    'BC'	=>	'BC - British Columbia',
    'MB'	=>	'MB - Manitoba',
    'NB'	=>	'NB - New Brunswick',
    'NL'	=>	'NL - Newfoundland and Labrador',
    'NT'	=>	'NT - Northwest Territories',
    'NS'	=>	'NS - Nova Scotia',
    'NU'	=>	'NU - Nunavut',
    'ON'	=>	'ON - Ontario',
    'PE'	=>	'PE - Prince Edward Island',
    'QC'	=>	'QC - Quebec',
    'SK'	=>	'SK - Saskatchewan',
    'YT'	=>	'YT - Yukon',
    
    'AAD'	=>	'---------------',
    
    'AS'	=>	'AS - American Samoa',
    'FM'	=>	'FM - Federated States of Micronesia',
    'GU'	=>	'GU - Guam',
    'MH'	=>	'MH - Marshall Islands',
    'MP'	=>	'MP - Northern Mariana Islands',
    'PW'	=>	'PW - Palau',
    'PR'	=>	'PR - Puerto Rico',
    'VI'	=>	'VI - Virgin Islands',
    
    'AAE'	=>	'---------------',
    
    'XX'	=>	'XX - Other State/Province/Territory',
);

/**
 * --------------------------
 * Config: Country List
 * --------------------------
 * Default value:
 * $config['country_list'] = array();
 * 
 * Contains the complete list of countries
 */
$config['country_list'] = array(
	"AF"=>"Afghanistan",
	"AL"=>"Albania",
	"DZ"=>"Algeria",
	"AD"=>"Andorra",
	"AO"=>"Angola",
	"AI"=>"Anguilla",
	"AQ"=>"Antarctica",
	"AG"=>"Antigua and Barbuda",
	"AR"=>"Argentina",
	"AM"=>"Armenia",
	"AW"=>"Aruba",
	"AU"=>"Australia",
	"AT"=>"Austria",
	"AZ"=>"Azerbaijan",
	"BS"=>"Bahamas",
	"BH"=>"Bahrain",
	"BD"=>"Bangladesh",
	"BB"=>"Barbados",
	"BY"=>"Belarus",
	"BE"=>"Belgium",
	"BZ"=>"Belize",
	"BJ"=>"Benin",
	"BM"=>"Bermuda",
	"BT"=>"Bhutan",
	"BO"=>"Bolivia",
	"BA"=>"Bosnia and Herzegovina",
	"BW"=>"Botswana",
	"BR"=>"Brazil",
	"IO"=>"British Indian Ocean",
	"BN"=>"Brunei",
	"BG"=>"Bulgaria",
	"BF"=>"Burkina Faso",
	"BI"=>"Burundi",
	"KH"=>"Cambodia",
	"CM"=>"Cameroon",
	"CA"=>"Canada",
	"CV"=>"Cape Verde",
	"KY"=>"Cayman Islands",
	"CF"=>"Central African Republic",
	"TD"=>"Chad",
	"CL"=>"Chile",
	"CN"=>"China",
	"CX"=>"Christmas Island",
	"CC"=>"Cocos (Keeling) Islands",
	"CO"=>"Colombia",
	"KM"=>"Comoros",
	"CD"=>"Congo, Democratic Republic of the",
	"CG"=>"Congo, Republic of the",
	"CK"=>"Cook Islands",
	"CR"=>"Costa Rica",
	"HR"=>"Croatia",
	"CY"=>"Cyprus",
	"CZ"=>"Czech Republic",
	"DK"=>"Denmark",
	"DJ"=>"Djibouti",
	"DM"=>"Dominica",
	"DO"=>"Dominican Republic",
	"TL"=>"East Timor",
	"EC"=>"Ecuador",
	"EG"=>"Egypt",
	"SV"=>"El Salvador",
	"GQ"=>"Equatorial Guinea",
	"ER"=>"Eritrea",
	"EE"=>"Estonia",
	"ET"=>"Ethiopia",
	"FK"=>"Falkland Islands (Malvinas)",
	"FO"=>"Faroe Islands",
	"FJ"=>"Fiji",
	"FI"=>"Finland",
	"FR"=>"France",
	"GF"=>"French Guiana",
	"PF"=>"French Polynesia",
	"GA"=>"Gabon",
	"GM"=>"Gambia",
	"GE"=>"Georgia",
	"DE"=>"Germany",
	"GH"=>"Ghana",
	"GI"=>"Gibraltar",
	"GR"=>"Greece",
	"GL"=>"Greenland",
	"GD"=>"Grenada",
	"GP"=>"Guadeloupe",
	"GT"=>"Guatemala",
	"GN"=>"Guinea",
	"GW"=>"Guinea-Bissau",
	"GY"=>"Guyana",
	"HT"=>"Haiti",
	"HN"=>"Honduras",
	"HK"=>"Hong Kong",
	"HU"=>"Hungary",
	"IS"=>"Iceland",
	"IN"=>"India",
	"ID"=>"Indonesia",
	"IE"=>"Ireland",
	"IL"=>"Israel",
	"IT"=>"Italy",
	"CI"=>"Ivory Coast (C&ocirc;te d\'Ivoire)",
	"JM"=>"Jamaica",
	"JP"=>"Japan",
	"JO"=>"Jordan",
	"KZ"=>"Kazakhstan",
	"KE"=>"Kenya",
	"KI"=>"Kiribati",
	"KR"=>"Korea, South",
	"KW"=>"Kuwait",
	"KG"=>"Kyrgyzstan",
	"LA"=>"Laos",
	"LV"=>"Latvia",
	"LB"=>"Lebanon",
	"LS"=>"Lesotho",
	"LI"=>"Liechtenstein",
	"LT"=>"Lithuania",
	"LU"=>"Luxembourg",
	"MO"=>"Macau",
	"MK"=>"Macedonia, Republic of",
	"MG"=>"Madagascar",
	"MW"=>"Malawi",
	"MY"=>"Malaysia",
	"MV"=>"Maldives",
	"ML"=>"Mali",
	"MT"=>"Malta",
	"MH"=>"Marshall Islands",
	"MQ"=>"Martinique",
	"MR"=>"Mauritania",
	"MU"=>"Mauritius",
	"YT"=>"Mayotte",
	"MX"=>"Mexico",
	"FM"=>"Micronesia",
	"MD"=>"Moldova",
	"MC"=>"Monaco",
	"MN"=>"Mongolia",
	"ME"=>"Montenegro",
	"MS"=>"Montserrat",
	"MA"=>"Morocco",
	"MZ"=>"Mozambique",
	"NA"=>"Namibia",
	"NR"=>"Nauru",
	"NP"=>"Nepal",
	"NL"=>"Netherlands",
	"AN"=>"Netherlands Antilles",
	"NC"=>"New Caledonia",
	"NZ"=>"New Zealand",
	"NI"=>"Nicaragua",
	"NE"=>"Niger",
	"NG"=>"Nigeria",
	"NU"=>"Niue",
	"NF"=>"Norfolk Island",
	"NO"=>"Norway",
	"OM"=>"Oman",
	"PK"=>"Pakistan",
	"PS"=>"Palestinian Territory",
	"PA"=>"Panama",
	"PG"=>"Papua New Guinea",
	"PY"=>"Paraguay",
	"PE"=>"Peru",
	"PH"=>"Philippines",
	"PN"=>"Pitcairn Island",
	"PL"=>"Poland",
	"PT"=>"Portugal",
	"QA"=>"Qatar",
	"RE"=>"R&eacute;union",
	"RO"=>"Romania",
	"RU"=>"Russia",
	"RW"=>"Rwanda",
	"SH"=>"Saint Helena",
	"KN"=>"Saint Kitts and Nevis",
	"LC"=>"Saint Lucia",
	"PM"=>"Saint Pierre and Miquelon",
	"VC"=>"Saint Vincent and the Grenadines",
	"WS"=>"Samoa",
	"SM"=>"San Marino",
	"ST"=>"S&atilde;o Tome and Principe",
	"SA"=>"Saudi Arabia",
	"SN"=>"Senegal",
	"RS"=>"Serbia",
	"CS"=>"Serbia and Montenegro",
	"SC"=>"Seychelles",
	"SL"=>"Sierra Leon",
	"SG"=>"Singapore",
	"SK"=>"Slovakia",
	"SI"=>"Slovenia",
	"SB"=>"Solomon Islands",
	"SO"=>"Somalia",
	"ZA"=>"South Africa",
	"GS"=>"South Georgia and the South Sandwich Islands",
	"ES"=>"Spain",
	"LK"=>"Sri Lanka",
	"SR"=>"Suriname",
	"SJ"=>"Svalbard and Jan Mayen",
	"SZ"=>"Swaziland",
	"SE"=>"Sweden",
	"CH"=>"Switzerland",
	"TW"=>"Taiwan",
	"TJ"=>"Tajikistan",
	"TZ"=>"Tanzania",
	"TH"=>"Thailand",
	"TG"=>"Togo",
	"TK"=>"Tokelau",
	"TO"=>"Tonga",
	"TT"=>"Trinidad and Tobago",
	"TN"=>"Tunisia",
	"TR"=>"Turkey",
	"TM"=>"Turkmenistan",
	"TC"=>"Turks and Caicos Islands",
	"TV"=>"Tuvalu",
	"UG"=>"Uganda",
	"UA"=>"Ukraine",
	"AE"=>"United Arab Emirates",
	"GB"=>"United Kingdom",
	"US"=>"United States",
	"UM"=>"United States Minor Outlying Islands",
	"UY"=>"Uruguay",
	"UZ"=>"Uzbekistan",
	"VU"=>"Vanuatu",
	"VA"=>"Vatican City",
	"VE"=>"Venezuela",
	"VN"=>"Vietnam",
	"VG"=>"Virgin Islands, British",
	"WF"=>"Wallis and Futuna",
	"EH"=>"Western Sahara",
	"YE"=>"Yemen",
	"ZM"=>"Zambia",
	"ZW"=>"Zimbabwe"
);

/**
 * --------------------------
 * Config: Top Country List
 * --------------------------
 * Default value:
 * $config['country_list'] = array('US','CA','GB','DE','BR','IT','ES','AU','NZ','HK');
 * 
 * Contains the top country list
 */
 $config['top_countries'] = array('US','CA');

/* End of file form.php */
/* Location: ./application/config/form.php */